# Generated by Django 3.0.5 on 2020-05-21 08:26

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
    ]
