# Generated by Django 3.0.5 on 2020-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200617_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='infos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prix / restauration'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
