# Generated by Django 3.0.5 on 2020-06-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200623_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Annonce'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Configuration'},
        ),
    ]
