# Generated by Django 3.0.5 on 2020-06-25 11:29

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200623_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='favicon',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Bannière'),
        ),
    ]
